### ISSUE TITLE
Pressing ENTER during scan causes gdu to crash

### ISSUE THREAD

**Issue by yacoob** [dundee/gdu#115]
This bug has been discovered by my cat :)

I have a directory which is couple TB in size. My cat decided to press ENTER while the scan was running. gdu crashed straight away, producing this stacktrace:

```
panic: interface conversion: interface {} is nil, not *analyze.File [recovered]
        panic: interface conversion: interface {} is nil, not *analyze.File

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000238000)
        github.com/rivo/tview/application.go:243 +0x87
panic(0x6670a0, 0xc003c72120)
        runtime/panic.go:969 +0x1b9
github.com/dundee/gdu/tui.(*UI).fileItemSelected(0xc00023c000, 0x0, 0x0)
        github.com/dundee/gdu/tui/tui.go:327 +0x125
github.com/rivo/tview.(*Table).InputHandler.func1(0xc0026b60a0, 0xc0004a80d0)
        github.com/rivo/tview/table.go:1238 +0x312
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0026b60a0, 0xc0004a80d0)
        github.com/rivo/tview/box.go:158 +0x62
github.com/rivo/tview.(*Grid).InputHandler.func1(0xc0026b60a0, 0xc0004a80d0)
        github.com/rivo/tview/grid.go:278 +0xb2
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0026b60a0, 0xc0004a80d0)
        github.com/rivo/tview/box.go:158 +0x62
github.com/rivo/tview.(*Pages).InputHandler.func1(0xc0026b60a0, 0xc0004a80d0)
        github.com/rivo/tview/pages.go:309 +0xb3
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0026b60a0, 0xc0004a80d0)
        github.com/rivo/tview/box.go:158 +0x62
github.com/rivo/tview.(*Application).Run(0xc000238000, 0x0, 0x0)
        github.com/rivo/tview/application.go:334 +0x6c2
github.com/dundee/gdu/tui.(*UI).StartUILoop(0xc00023c000, 0x7ffdbd1d2a27, 0x8)
        github.com/dundee/gdu/tui/tui.go:222 +0x33
github.com/dundee/gdu/cmd.Run(0xc000072e10, 0xc000044b80, 0x1, 0x1, 0xc00010f001, 0x6f4760, 0xc000010018, 0x6f9520, 0xc000238000, 0x6f5ca0, ...)
        github.com/dundee/gdu/cmd/run.go:91 +0x339
main.main.func1(0xc00011b680, 0xc000044b80, 0x1, 0x1, 0x0, 0x0)
        github.com/dundee/gdu/main.go:52 +0x125
github.com/spf13/cobra.(*Command).execute(0xc00011b680, 0xc00000e0b0, 0x1, 0x1, 0xc00011b680, 0xc00000e0b0)
        github.com/spf13/cobra/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00011b680, 0xc000072e3e, 0x6a7cb0, 0x8)
        github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:897
main.main()
        github.com/dundee/gdu/main.go:67 +0x505
```

Judging from the function names, the input handler tries to handle an item selection way before any list of dirs is ready.

**Comment by yacoob** [comment]
...actually, this is an old version of gdu that my cat has crashed. I've checked a more recent version (5.8.1-2~bpo11+1 from debian's bullseye-backports) and educated my cat about doing more verification before filing a bug. Nothing to do here! :)
