### ISSUE TITLE
[bug] cannot enter interaction mode in mintty

### ISSUE THREAD

**Issue by Freed-Wu** [dundee/gdu#144]
In conhost (the default terminal emulator for windows), gdu can work. However, in mintty (the default terminal emulator for cygwin/msys2), `gdu` will behave like `gdu -n`.

Thanks.

**Comment by Freed-Wu** [comment]
And I try to compile it and found the test failed. Is it reasonable?

```
?       github.com/dundee/gdu/v5/build  [no test files]
?       github.com/dundee/gdu/v5/cmd/gdu        [no test files]
--- FAIL: TestAnalyzePath (0.00s)
    app_test.go:46:
                Error Trace:    app_test.go:46
                Error:          "" does not contain "nested"
                Test:           TestAnalyzePath
    app_test.go:47:
                Error Trace:    app_test.go:47
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000129290)}
                Test:           TestAnalyzePath
--- FAIL: TestAnalyzePathProfiling (0.00s)
    app_test.go:61:
                Error Trace:    app_test.go:61
                Error:          "" does not contain "nested"
                Test:           TestAnalyzePathProfiling
    app_test.go:62:
                Error Trace:    app_test.go:62
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000129620)}
                Test:           TestAnalyzePathProfiling
--- FAIL: TestAnalyzePathWithIgnoring (0.00s)
    app_test.go:80:
                Error Trace:    app_test.go:80
                Error:          "" does not contain "nested"
                Test:           TestAnalyzePathWithIgnoring
    app_test.go:81:
                Error Trace:    app_test.go:81
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc0001299b0)}
                Test:           TestAnalyzePathWithIgnoring
--- FAIL: TestAnalyzePathWithGui (0.00s)
    app_test.go:134:
                Error Trace:    app_test.go:134
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc0001860c0)}
                Test:           TestAnalyzePathWithGui
--- FAIL: TestAnalyzePathWithExport (0.00s)
    app_test.go:151:
                Error Trace:    app_test.go:151
                Error:          Should NOT be empty, but was
                Test:           TestAnalyzePathWithExport
    app_test.go:152:
                Error Trace:    app_test.go:152
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000186360)}
                Test:           TestAnalyzePathWithExport
--- FAIL: TestReadAnalysisFromFile (0.00s)
    app_test.go:163:
                Error Trace:    app_test.go:163
                Error:          Should NOT be empty, but was
                Test:           TestReadAnalysisFromFile
    app_test.go:164:
                Error Trace:    app_test.go:164
                Error:          "" does not contain "main.go"
                Test:           TestReadAnalysisFromFile
    app_test.go:165:
                Error Trace:    app_test.go:165
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000186690)}
                Test:           TestReadAnalysisFromFile
--- FAIL: TestReadWrongAnalysisFromFile (0.00s)
    app_test.go:177:
                Error Trace:    app_test.go:177
                Error:          "opening log file: open /dev/null: The system cannot find the path specified." does not contain "Array of maps not found"
                Test:           TestReadWrongAnalysisFromFile
--- FAIL: TestReadWrongAnalysisFromNotExistingFile (0.00s)
    app_test.go:189:
                Error Trace:    app_test.go:189
                Error:          "opening log file: open /dev/null: The system cannot find the path specified." does not contain "no such file or directory"
                Test:           TestReadWrongAnalysisFromNotExistingFile
--- FAIL: TestAnalyzePathWithErr (0.00s)
    app_test.go:210:
                Error Trace:    app_test.go:210
                Error:          "opening log file: open /dev/null: The system cannot find the path specified." does not contain "no such file or directory"
                Test:           TestAnalyzePathWithErr
--- FAIL: TestNoCross (0.00s)
    app_test.go:224:
                Error Trace:    app_test.go:224
                Error:          "" does not contain "nested"
                Test:           TestNoCross
    app_test.go:225:
                Error Trace:    app_test.go:225
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000187020)}
                Test:           TestNoCross
--- FAIL: TestListDevices (0.00s)
    app_test.go:239:
                Error Trace:    app_test.go:239
                Error:          "" does not contain "Device"
                Test:           TestListDevices
    app_test.go:240:
                Error Trace:    app_test.go:240
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc0001873b0)}
                Test:           TestListDevices
--- FAIL: TestListDevicesToFile (0.03s)
    app_test.go:258:
                Error Trace:    app_test.go:258
                Error:          "opening log file: open /dev/null: The system cannot find the path specified." does not contain "not supported"
                Test:           TestListDevicesToFile
--- FAIL: TestListDevicesWithGui (0.01s)
    app_test.go:272:
                Error Trace:    app_test.go:272
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000187a10)}
                Test:           TestListDevicesWithGui
--- FAIL: TestMaxCores (0.00s)
    app_test.go:285:
                Error Trace:    app_test.go:285
                Error:          Expected nil, but got: &fmt.wrapError{msg:"opening log file: open /dev/null: The system cannot find the path specified.", err:(*fs.PathError)(0xc000187c20)}
                Test:           TestMaxCores
FAIL
FAIL    github.com/dundee/gdu/v5/cmd/gdu/app    0.233s
ok      github.com/dundee/gdu/v5/internal/common        0.190s
?       github.com/dundee/gdu/v5/internal/testanalyze   [no test files]
?       github.com/dundee/gdu/v5/internal/testapp       [no test files]
?       github.com/dundee/gdu/v5/internal/testdev       [no test files]
?       github.com/dundee/gdu/v5/internal/testdir       [no test files]
--- FAIL: TestFlags (0.00s)
    dir_test.go:101:
                Error Trace:    dir_test.go:101
                Error:          Not equal:
                                expected: 16412
                                actual  : 16391
                Test:           TestFlags
    dir_test.go:107:
                Error Trace:    dir_test.go:107
                Error:          Not equal:
                                expected: 21
                                actual  : 0
                Test:           TestFlags
--- FAIL: TestHardlink (0.00s)
    dir_test.go:127:
                Error Trace:    dir_test.go:127
                Error:          Not equal:
                                expected: 12295
                                actual  : 12297
                Test:           TestHardlink
    dir_test.go:133:
                Error Trace:    dir_test.go:133
                Error:          Not equal:
                                expected: 72
                                actual  : 32
                Test:           TestHardlink
--- FAIL: TestErr (0.00s)
    dir_test.go:155:
                Error Trace:    dir_test.go:155
                Error:          Not equal:
                                expected: 2
                                actual  : 5
                Test:           TestErr
    dir_test.go:156:
                Error Trace:    dir_test.go:156
                Error:          Not equal:
                                expected: 46
                                actual  : 32
                Test:           TestErr
    dir_test.go:159:
                Error Trace:    dir_test.go:159
                Error:          Not equal:
                                expected: 33
                                actual  : 32
                Test:           TestErr
--- FAIL: TestRemoveFileWithErr (0.00s)
    file_test.go:254:
                Error Trace:    file_test.go:254
                                                        panic.go:838
                                                        panic.go:220
                                                        signal_windows.go:255
                                                        file_test.go:272
                Error:          Expected nil, but got: &fs.PathError{Op:"chmod", Path:"test_dir/nested", Err:0x2}
                Test:           TestRemoveFileWithErr
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x5be909]

goroutine 54 [running]:
testing.tRunner.func1.2({0x5e4420, 0x7a4da0})
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x5e4420, 0x7a4da0})
        C:/msys64/mingw64/lib/go/src/runtime/panic.go:838 +0x207
github.com/dundee/gdu/v5/pkg/analyze.TestRemoveFileWithErr(0xc000169040)
        C:/Users/wzy/Desktop/MINGW-packages/mingw-w64-gdu/src/gdu-5.13.2/pkg/analyze/file_test.go:272 +0x1e9
testing.tRunner(0xc000169040, 0x62f9c0)
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1486 +0x35f
FAIL    github.com/dundee/gdu/v5/pkg/analyze    0.227s
ok      github.com/dundee/gdu/v5/pkg/device     (cached)
?       github.com/dundee/gdu/v5/pkg/fs [no test files]
--- FAIL: TestReadAnalysis (0.00s)
    import_test.go:36:
                Error Trace:    import_test.go:36
                Error:          Not equal:
                                expected: "/home/xxx"
                                actual  : "\\home\\xxx"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -/home/xxx
                                +\home\xxx
                Test:           TestReadAnalysis
FAIL
FAIL    github.com/dundee/gdu/v5/report 0.710s
ok      github.com/dundee/gdu/v5/stdout (cached)
--- FAIL: TestViewFile (0.00s)
panic: remove test_dir\nested\file2: The process cannot access the file because it is being used by another process. [recovered]
        panic: remove test_dir\nested\file2: The process cannot access the file because it is being used by another process.

goroutine 33 [running]:
testing.tRunner.func1.2({0x503b80, 0xc000126a50})
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x503b80, 0xc000126a50})
        C:/msys64/mingw64/lib/go/src/runtime/panic.go:838 +0x207
github.com/dundee/gdu/v5/internal/testdir.CreateTestDir.func1()
        C:/Users/wzy/Desktop/MINGW-packages/mingw-w64-gdu/src/gdu-5.13.2/internal/testdir/test_dir.go:22 +0x3f
github.com/dundee/gdu/v5/tui.TestViewFile(0xc0000e8340?)
        C:/Users/wzy/Desktop/MINGW-packages/mingw-w64-gdu/src/gdu-5.13.2/tui/actions_test.go:272 +0x50f
testing.tRunner(0xc0000e8340, 0x559a90)
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        C:/msys64/mingw64/lib/go/src/testing/testing.go:1486 +0x35f
FAIL    github.com/dundee/gdu/v5/tui    0.223s
FAIL
```

**Comment by dundee** [comment]
Gdu is using https://github.com/mattn/go-isatty for detecting if is running in interactive terminal. I am not sure if it supports mintty. I will try to check that.

**Comment by Freed-Wu** [comment]
I think <https://github.com/mattn/go-isatty> cannot support mintty. Because not only one software has this bug, <https://github.com/junegunn/fzf> is same, and it also use <https://github.com/mattn/go-isatty> to detect tty.

**Comment by Freed-Wu** [comment]
See <https://github.com/msys2/MINGW-packages/pull/11662#issuecomment-1146853457>, use a shell script to wrap it can avoid this bug. (Although it is a little troublesome.)

**Comment by Freed-Wu** [comment]
Note winpty only work when stdin and stdout is a tty, such as `winpty XXX`, not `winpty XXX | YYY`. See `https://github.com/rprichard/winpty/issues/101`. So it is still not a perfect solution.

**Comment by Freed-Wu** [comment]
Hey, I found windows terminal can solve this problem! Mintty don't support win32 console API and only support ANSI Escape Code, so many win32 native programs cannot work normally. winpty just only open an invisible conhost window to wrap these win32 native programs.
