### ISSUE TITLE
Using "-i" flag causes "runtime error"

### ISSUE THREAD

**Issue by afedulov** [dundee/gdu#60]
Whenever I try to add an ignored directory, `gdu` fails with:

```
runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5a17a2]
```

With some output dumped below the "Scanning..." window:

```
goroutine 1646 [running]:                                                                                                                                                                                                    
github.com/dundee/gdu/v4/analyze.getFlag(0x0, 0x0, 0x1)                                                                                                                                             
github.com/dundee/gdu/v4/analyze/dir.go:167 +0x22                                                                                      
github.com/dundee/gdu/v4/analyze.(*ParallelAnalyzer).processDir(0xc0000c25c0, 0xc0009efbe0, 0xe, 0x0)                                                                                                                                                                                        
github.com/dundee/gdu/v4/analyze/dir.go:128 +0x48c                                                                                                                                     
github.com/dundee/gdu/v4/analyze.(*ParallelAnalyzer).processDir.func1(0xc0000c25c0, 0xc0009efbe0, 0xe, 0xc0008540c0, 0xc0009ef960)   
github.com/dundee/gdu/v4/analyze/dir.go:114 +0x5d                                                                                                                                                       
created by github.com/dundee/gdu/v4/analyze.(*ParallelAnalyzer).processDir                                                                             
github.com/dundee/gdu/v4/analyze/dir.go:112 +0x3fb
```

Executed command:
```
# ran as sudo
/home/linuxbrew/.linuxbrew/bin/gdu -i /media/alex/Jumbo
```

If I add  the directory where it failed to the list of ignored directories, it fails at other random places, including files in the home folder.

Environment:
```
Linux Mint 19
gdu version: v4.8.0
```

**Comment by dundee** [comment]
Please upgrade to the latest version (5.1.0), where this bug is fixed.

```bash
brew upgrade gdu
```
